
// authentication
export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS ='SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE ='SIGNUP_USER_FAILURE';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS ='LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE ='LOGIN_USER_FAILURE';


export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS ='LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE ='LOGOUT_USER_FAILURE';

export const PROFILE_BIO_REQUEST= 'PROFILE_BIO_REQUEST';
export const PROFILE_BIO_SUCCESS = 'PROFILE_BIO_SUCCESS';